services:
  db:
    build:
      context: ./backend
      dockerfile: postgres/Dockerfile
    container_name: getapet_db
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build: ./backend
    container_name: getapet_backend
    depends_on:
      - db
    env_file:
      - .env
    ports:
      - "8080:8080"
    command: sh -c "swag init -d ./cmd,./internal -g main.go --parseInternal --parseDependency --parseDepth 2 -o ./docs && go run ./cmd"

  test:
    build: ./backend
    depends_on:
      - db
    env_file:
      - .env
    command: go test ./...

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.14.3
    container_name: getapet_elasticsearch
    profiles:
      - metrics
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
    ports:
      - "9200:9200"
    volumes:
      - esdata:/usr/share/elasticsearch/data

  kibana:
    image: docker.elastic.co/kibana/kibana:8.14.3
    container_name: getapet_kibana
    profiles:
      - metrics
    depends_on:
      - elasticsearch
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports:
      - "5601:5601"

volumes:
  pgdata:
  esdata:

