services:
  n8n:
    image: n8nio/n8n:latest
    container_name: n8n
    restart: unless-stopped
    ports:
      - "5678:5678"
    environment:
      - N8N_HOST=cherryl-envious-comparably.ngrok-free.dev
      - N8N_PROTOCOL=https
      - WEBHOOK_URL=https://cherryl-envious-comparably.ngrok-free.dev
      - N8N_SECURE_COOKIE=false  # Важно для ngrok
      - N8N_METRICS=false        # Опционально, отключает метрики
    volumes:
      - n8n_data:/home/node/.n8n

volumes:
  n8n_data:
    driver: local