// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/pets": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "pets"
                ],
                "summary": "Получить список питомцев",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/dto.PetResponse"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/delivery_http_pet.ErrorResponse"
                        }
                    },
                    "503": {
                        "description": "Service Unavailable",
                        "schema": {
                            "$ref": "#/definitions/delivery_http_pet.ErrorResponse"
                        }
                    }
                }
            },
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "pets"
                ],
                "summary": "Создать питомца",
                "parameters": [
                    {
                        "description": "Данные питомца",
                        "name": "pet",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.CreatePetRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/dto.PetResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/delivery_http_pet.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/delivery_http_pet.ErrorResponse"
                        }
                    },
                    "503": {
                        "description": "Service Unavailable",
                        "schema": {
                            "$ref": "#/definitions/delivery_http_pet.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/pets/{id}": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "pets"
                ],
                "summary": "Получить питомца по ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID питомца",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.PetResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/delivery_http_pet.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/delivery_http_pet.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/delivery_http_pet.ErrorResponse"
                        }
                    },
                    "503": {
                        "description": "Service Unavailable",
                        "schema": {
                            "$ref": "#/definitions/delivery_http_pet.ErrorResponse"
                        }
                    }
                }
            },
            "put": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "pets"
                ],
                "summary": "Обновить питомца",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID питомца",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Обновленные данные питомца",
                        "name": "pet",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.UpdatePetRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.PetResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/delivery_http_pet.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/delivery_http_pet.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/delivery_http_pet.ErrorResponse"
                        }
                    },
                    "503": {
                        "description": "Service Unavailable",
                        "schema": {
                            "$ref": "#/definitions/delivery_http_pet.ErrorResponse"
                        }
                    }
                }
            },
            "delete": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "pets"
                ],
                "summary": "Удалить питомца",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID питомца",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/delivery_http_pet.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/delivery_http_pet.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/delivery_http_pet.ErrorResponse"
                        }
                    },
                    "503": {
                        "description": "Service Unavailable",
                        "schema": {
                            "$ref": "#/definitions/delivery_http_pet.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/users": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "Get all users",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/dto.UserResponse"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/delivery_http_user.ErrorResponse"
                        }
                    },
                    "503": {
                        "description": "Service Unavailable",
                        "schema": {
                            "$ref": "#/definitions/delivery_http_user.ErrorResponse"
                        }
                    }
                }
            },
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "Create user",
                "parameters": [
                    {
                        "description": "User payload",
                        "name": "user",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.CreateUserRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/dto.RegisterResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/delivery_http_user.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/delivery_http_user.ErrorResponse"
                        }
                    },
                    "503": {
                        "description": "Service Unavailable",
                        "schema": {
                            "$ref": "#/definitions/delivery_http_user.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/users/login": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "Login user",
                "parameters": [
                    {
                        "description": "Login credentials",
                        "name": "user",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.LoginRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.LoginResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/delivery_http_user.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/delivery_http_user.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/delivery_http_user.ErrorResponse"
                        }
                    },
                    "503": {
                        "description": "Service Unavailable",
                        "schema": {
                            "$ref": "#/definitions/delivery_http_user.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/users/{id}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "Get user by ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "User ID (UUID)",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.UserResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/delivery_http_user.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/delivery_http_user.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/delivery_http_user.ErrorResponse"
                        }
                    },
                    "503": {
                        "description": "Service Unavailable",
                        "schema": {
                            "$ref": "#/definitions/delivery_http_user.ErrorResponse"
                        }
                    }
                }
            },
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "Update user",
                "parameters": [
                    {
                        "type": "string",
                        "description": "User ID (UUID)",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "User data",
                        "name": "user",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.UpdateUserRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.UserResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/delivery_http_user.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/delivery_http_user.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/delivery_http_user.ErrorResponse"
                        }
                    },
                    "503": {
                        "description": "Service Unavailable",
                        "schema": {
                            "$ref": "#/definitions/delivery_http_user.ErrorResponse"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "tags": [
                    "users"
                ],
                "summary": "Delete user",
                "parameters": [
                    {
                        "type": "string",
                        "description": "User ID (UUID)",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/delivery_http_user.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/delivery_http_user.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/delivery_http_user.ErrorResponse"
                        }
                    },
                    "503": {
                        "description": "Service Unavailable",
                        "schema": {
                            "$ref": "#/definitions/delivery_http_user.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/vet-passports": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "vet-passports"
                ],
                "summary": "Получить список ветпаспортов",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/dto.VetPassportResponse"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/delivery_http_vetpassport.ErrorResponse"
                        }
                    },
                    "503": {
                        "description": "Service Unavailable",
                        "schema": {
                            "$ref": "#/definitions/delivery_http_vetpassport.ErrorResponse"
                        }
                    }
                }
            },
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "vet-passports"
                ],
                "summary": "Создать ветпаспорт",
                "parameters": [
                    {
                        "description": "Данные ветпаспорта",
                        "name": "passport",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.CreateVetPassportRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/dto.VetPassportResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/delivery_http_vetpassport.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/delivery_http_vetpassport.ErrorResponse"
                        }
                    },
                    "503": {
                        "description": "Service Unavailable",
                        "schema": {
                            "$ref": "#/definitions/delivery_http_vetpassport.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/vet-passports/{id}": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "vet-passports"
                ],
                "summary": "Получить ветпаспорт по ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID ветпаспорта",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.VetPassportResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/delivery_http_vetpassport.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/delivery_http_vetpassport.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/delivery_http_vetpassport.ErrorResponse"
                        }
                    },
                    "503": {
                        "description": "Service Unavailable",
                        "schema": {
                            "$ref": "#/definitions/delivery_http_vetpassport.ErrorResponse"
                        }
                    }
                }
            },
            "put": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "vet-passports"
                ],
                "summary": "Обновить ветпаспорт",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID ветпаспорта",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Обновленные данные",
                        "name": "passport",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.UpdateVetPassportRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.VetPassportResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/delivery_http_vetpassport.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/delivery_http_vetpassport.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/delivery_http_vetpassport.ErrorResponse"
                        }
                    },
                    "503": {
                        "description": "Service Unavailable",
                        "schema": {
                            "$ref": "#/definitions/delivery_http_vetpassport.ErrorResponse"
                        }
                    }
                }
            },
            "delete": {
                "tags": [
                    "vet-passports"
                ],
                "summary": "Удалить ветпаспорт",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID ветпаспорта",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/delivery_http_vetpassport.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/delivery_http_vetpassport.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/delivery_http_vetpassport.ErrorResponse"
                        }
                    },
                    "503": {
                        "description": "Service Unavailable",
                        "schema": {
                            "$ref": "#/definitions/delivery_http_vetpassport.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/health": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "system"
                ],
                "summary": "Check service health",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/delivery_http.HealthResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "delivery_http.HealthResponse": {
            "type": "object",
            "properties": {
                "status": {
                    "type": "string"
                }
            }
        },
        "delivery_http_pet.ErrorResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string"
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "delivery_http_user.ErrorResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string"
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "delivery_http_vetpassport.ErrorResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string"
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "dto.CreatePetRequest": {
            "type": "object",
            "required": [
                "color",
                "pet_age",
                "pet_gender",
                "pet_name",
                "price",
                "species"
            ],
            "properties": {
                "breed": {
                    "type": "string",
                    "maxLength": 100,
                    "example": "british"
                },
                "color": {
                    "type": "string",
                    "maxLength": 50,
                    "example": "black"
                },
                "good_with_animals": {
                    "type": "boolean",
                    "example": false
                },
                "good_with_children": {
                    "type": "boolean",
                    "example": true
                },
                "pedigree": {
                    "type": "boolean",
                    "example": true
                },
                "pet_age": {
                    "type": "integer",
                    "maximum": 50,
                    "minimum": 0,
                    "example": 2
                },
                "pet_description": {
                    "type": "string",
                    "maxLength": 1000,
                    "example": "Очень дружелюбный и активный питомец"
                },
                "pet_gender": {
                    "type": "string",
                    "enum": [
                        "male",
                        "female"
                    ],
                    "example": "male"
                },
                "pet_name": {
                    "type": "string",
                    "maxLength": 100,
                    "minLength": 1,
                    "example": "Барсик"
                },
                "price": {
                    "type": "number",
                    "minimum": 0,
                    "example": 15000
                },
                "species": {
                    "type": "string",
                    "enum": [
                        "cat",
                        "dog",
                        "bird",
                        "other"
                    ],
                    "example": "cat"
                },
                "vet_passport_id": {
                    "type": "string",
                    "example": "uuid"
                }
            }
        },
        "dto.CreateUserRequest": {
            "type": "object",
            "required": [
                "fio",
                "telephone_number",
                "user_login",
                "user_password"
            ],
            "properties": {
                "city": {
                    "type": "string",
                    "maxLength": 50,
                    "example": "Saint Petersburg"
                },
                "fio": {
                    "type": "string",
                    "maxLength": 255,
                    "minLength": 1,
                    "example": "Петрова Мария Сергеевна"
                },
                "status": {
                    "type": "string",
                    "enum": [
                        "active",
                        "blocked"
                    ],
                    "example": "active"
                },
                "telephone_number": {
                    "type": "string",
                    "maxLength": 20,
                    "minLength": 5,
                    "example": "+79998887766"
                },
                "user_description": {
                    "type": "string",
                    "maxLength": 1000,
                    "example": "Волонтёр приюта"
                },
                "user_login": {
                    "type": "string",
                    "maxLength": 50,
                    "minLength": 3,
                    "example": "maria_petrova"
                },
                "user_password": {
                    "type": "string",
                    "maxLength": 255,
                    "minLength": 6,
                    "example": "securepassword123"
                }
            }
        },
        "dto.CreateVetPassportRequest": {
            "type": "object",
            "properties": {
                "chipping": {
                    "type": "boolean",
                    "example": true
                },
                "health_issues": {
                    "type": "string",
                    "maxLength": 1000,
                    "example": "Аллергия на корм"
                },
                "parasite_treatments": {
                    "type": "string",
                    "maxLength": 1000,
                    "example": "Обработка от блох"
                },
                "sterilization": {
                    "type": "boolean",
                    "example": false
                },
                "vaccinations": {
                    "type": "string",
                    "maxLength": 1000,
                    "example": "Привит от бешенства"
                }
            }
        },
        "dto.LoginRequest": {
            "type": "object",
            "required": [
                "user_login",
                "user_password"
            ],
            "properties": {
                "user_login": {
                    "type": "string",
                    "maxLength": 50,
                    "minLength": 3,
                    "example": "maria_petrova"
                },
                "user_password": {
                    "type": "string",
                    "maxLength": 255,
                    "minLength": 6,
                    "example": "securepassword123"
                }
            }
        },
        "dto.LoginResponse": {
            "type": "object",
            "properties": {
                "token": {
                    "type": "string",
                    "example": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiNTUwZTg0MDAtZTI5Yi00MWQ0LWE3MTYtNDQ2NjU1NDQwMDAwIiwiaXNfYWRtaW4iOmZhbHNlLCJleHAiOjE3MDAwMDAwMDB9"
                },
                "user_id": {
                    "type": "string",
                    "example": "550e8400-e29b-41d4-a716-446655440000"
                }
            }
        },
        "dto.PetResponse": {
            "type": "object",
            "properties": {
                "breed": {
                    "type": "string",
                    "example": "british"
                },
                "color": {
                    "type": "string",
                    "example": "black"
                },
                "good_with_animals": {
                    "type": "boolean",
                    "example": false
                },
                "good_with_children": {
                    "type": "boolean",
                    "example": true
                },
                "id": {
                    "type": "string",
                    "example": "550e8400-e29b-41d4-a716-446655440000"
                },
                "pedigree": {
                    "type": "boolean",
                    "example": true
                },
                "pet_age": {
                    "type": "integer",
                    "example": 2
                },
                "pet_description": {
                    "type": "string",
                    "example": "Очень дружелюбный"
                },
                "pet_gender": {
                    "type": "string",
                    "example": "male"
                },
                "pet_name": {
                    "type": "string",
                    "example": "Барсик"
                },
                "price": {
                    "type": "number",
                    "example": 15000
                },
                "species": {
                    "type": "string",
                    "example": "cat"
                }
            }
        },
        "dto.RegisterResponse": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string",
                    "example": "550e8400-e29b-41d4-a716-446655440000"
                }
            }
        },
        "dto.UpdatePetRequest": {
            "type": "object",
            "required": [
                "color",
                "pet_age",
                "pet_gender",
                "pet_name",
                "price",
                "species"
            ],
            "properties": {
                "breed": {
                    "type": "string",
                    "maxLength": 100,
                    "example": "british"
                },
                "color": {
                    "type": "string",
                    "maxLength": 50,
                    "example": "black"
                },
                "good_with_animals": {
                    "type": "boolean",
                    "example": false
                },
                "good_with_children": {
                    "type": "boolean",
                    "example": true
                },
                "pedigree": {
                    "type": "boolean",
                    "example": true
                },
                "pet_age": {
                    "type": "integer",
                    "maximum": 50,
                    "minimum": 0,
                    "example": 3
                },
                "pet_description": {
                    "type": "string",
                    "maxLength": 1000,
                    "example": "Спокойный и ласковый"
                },
                "pet_gender": {
                    "type": "string",
                    "enum": [
                        "male",
                        "female"
                    ],
                    "example": "male"
                },
                "pet_name": {
                    "type": "string",
                    "maxLength": 100,
                    "minLength": 1,
                    "example": "Барсик"
                },
                "price": {
                    "type": "number",
                    "minimum": 0,
                    "example": 18000
                },
                "species": {
                    "type": "string",
                    "enum": [
                        "cat",
                        "dog",
                        "bird",
                        "other"
                    ],
                    "example": "cat"
                }
            }
        },
        "dto.UpdateUserRequest": {
            "type": "object",
            "required": [
                "fio",
                "status",
                "telephone_number",
                "user_login",
                "user_password"
            ],
            "properties": {
                "city": {
                    "type": "string",
                    "maxLength": 50,
                    "example": "Kazan"
                },
                "fio": {
                    "type": "string",
                    "maxLength": 255,
                    "minLength": 1,
                    "example": "Петрова Мария Сергеевна"
                },
                "status": {
                    "type": "string",
                    "enum": [
                        "active",
                        "blocked"
                    ],
                    "example": "active"
                },
                "telephone_number": {
                    "type": "string",
                    "maxLength": 20,
                    "minLength": 5,
                    "example": "+79998887766"
                },
                "user_description": {
                    "type": "string",
                    "maxLength": 1000,
                    "example": "Обновленное описание"
                },
                "user_login": {
                    "type": "string",
                    "maxLength": 50,
                    "minLength": 3,
                    "example": "maria_new_login"
                },
                "user_password": {
                    "type": "string",
                    "maxLength": 255,
                    "minLength": 6,
                    "example": "newsecurepassword123"
                }
            }
        },
        "dto.UpdateVetPassportRequest": {
            "type": "object",
            "properties": {
                "chipping": {
                    "type": "boolean",
                    "example": true
                },
                "health_issues": {
                    "type": "string",
                    "maxLength": 1000,
                    "example": "Нет"
                },
                "parasite_treatments": {
                    "type": "string",
                    "maxLength": 1000,
                    "example": "Регулярная обработка"
                },
                "sterilization": {
                    "type": "boolean",
                    "example": true
                },
                "vaccinations": {
                    "type": "string",
                    "maxLength": 1000,
                    "example": "Все прививки сделаны"
                }
            }
        },
        "dto.UserResponse": {
            "type": "object",
            "properties": {
                "city": {
                    "type": "string",
                    "example": "Moscow"
                },
                "fio": {
                    "type": "string",
                    "example": "Иванов Иван Иванович"
                },
                "status": {
                    "type": "string",
                    "example": "active"
                },
                "telephone_number": {
                    "type": "string",
                    "example": "+79991234567"
                },
                "user_description": {
                    "type": "string",
                    "example": "Люблю животных"
                },
                "user_login": {
                    "type": "string",
                    "example": "ivan_ivanov"
                }
            }
        },
        "dto.VetPassportResponse": {
            "type": "object",
            "properties": {
                "chipping": {
                    "type": "boolean",
                    "example": true
                },
                "health_issues": {
                    "type": "string",
                    "example": "Нет"
                },
                "id": {
                    "type": "string",
                    "example": "550e8400-e29b-41d4-a716-446655440000"
                },
                "parasite_treatments": {
                    "type": "string",
                    "example": "Обработан"
                },
                "sterilization": {
                    "type": "boolean",
                    "example": false
                },
                "vaccinations": {
                    "type": "string",
                    "example": "Привит"
                }
            }
        }
    },
    "securityDefinitions": {
        "BearerAuth": {
            "description": "Enter only JWT token (without Bearer prefix)",
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "GetAPet Backend API",
	Description:      "An aggregator of pet lists from shelters and private individuals.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}